services:
  nginx:
    build:
      context: .
    image: obcinko-nginx:1.1
    container_name: obcinko
    networks:
      - proxy
    env_file:
      - .env
    labels:
      - traefik.enable=true
      # - traefik.http.routers.obcinko.rule=HostRegexp(`(www|)obcinko.si`)
      - traefik.http.routers.obcinko.rule=HostRegexp(`^(www\.obcinko\.si|obcinko\.si)$`)
      - traefik.http.services.obcinko.loadbalancer.server.port=80
      - traefik.http.routers.obcinko.entrypoints=websecure
      - traefik.http.routers.obcinko.tls=true

      # middlewares
      - traefik.http.routers.obcinko.middlewares=mywwwredirect

networks:
  proxy:
    name: proxy
    external: true